botToken: abcdef123456789
botUsername: sample_username
chats:
  - -1234567890123
serverStartMessage: 'Server started.'
serverStopMessage: 'Server stopped.'
logJoinLeave: true
logFromMCtoTG: true
logFromTGtoMC: true
logDeath : true
worldTime: 'world_name'
strings:
  online: '<b>Online</b>'
  nobodyOnline: '<b>Nobody online...</b>'
  joined: 'has joined the game!'
  left: 'has left the game!'
